// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2023-2026 Mark Yu

import { byId } from "../utils/dom.js";

export type DomRefs = {
  runBtn: HTMLButtonElement;
  runModeBtn: HTMLButtonElement;
  runGroup: HTMLDivElement;
  runMenu: HTMLDivElement;
  runAllBtn: HTMLButtonElement;
  runSelBtn: HTMLButtonElement;
  runCellBtn: HTMLButtonElement;
  runLabel: HTMLSpanElement;
  openBtn: HTMLButtonElement;
  saveBtn: HTMLButtonElement;
  workspaceToggleBtn: HTMLButtonElement;
  shareBtn: HTMLButtonElement;
  fileInput: HTMLInputElement;
  directoryInput: HTMLInputElement;
  moreBtn: HTMLButtonElement;
  moreMenu: HTMLDivElement;
  shareMenuBtn: HTMLButtonElement;
  historyBtn: HTMLButtonElement;
  shortcutsBtn: HTMLButtonElement;
  resetBtn: HTMLButtonElement;
  settingsBtn: HTMLButtonElement;
  aboutBtn: HTMLButtonElement;
  undoBtn: HTMLButtonElement;
  redoBtn: HTMLButtonElement;
  findBtn: HTMLButtonElement;
  wrapBtn: HTMLButtonElement;
  editorActionsBtn: HTMLButtonElement;
  editorActionsMenu: HTMLDivElement;
  renameTabBtn: HTMLButtonElement;
  closeTabBtn: HTMLButtonElement;
  workspaceLayout: HTMLDivElement;
  editorPane: HTMLDivElement;
  workspacePane: HTMLElement;
  workspaceResizer: HTMLDivElement;
  workspaceNewBtn: HTMLButtonElement;
  workspaceUploadBtn: HTMLButtonElement;
  workspaceRenameBtn: HTMLButtonElement;
  workspaceDownloadBtn: HTMLButtonElement;
  workspaceDeleteBtn: HTMLButtonElement;
  workspaceCloseBtn: HTMLButtonElement;
  workspaceMeta: HTMLDivElement;
  workspaceTree: HTMLDivElement;
  workspaceUploadOverlay: HTMLDivElement;
  workspaceUploadFileChoiceBtn: HTMLButtonElement;
  workspaceUploadFolderChoiceBtn: HTMLButtonElement;
  workspaceUploadCancelBtn: HTMLButtonElement;
  editorSurface: HTMLDivElement;
  filePreviewPane: HTMLDivElement;
  filePreviewMeta: HTMLDivElement;
  filePreviewBody: HTMLDivElement;
  findBar: HTMLDivElement;
  findInput: HTMLInputElement;
  findCount: HTMLSpanElement;
  findReplaceModeBtn: HTMLButtonElement;
  findPrevBtn: HTMLButtonElement;
  findNextBtn: HTMLButtonElement;
  findCloseBtn: HTMLButtonElement;
  replaceRow: HTMLDivElement;
  replaceInput: HTMLInputElement;
  replaceBtn: HTMLButtonElement;
  replaceAllBtn: HTMLButtonElement;
  findCaseToggle: HTMLButtonElement;
  findWordToggle: HTMLButtonElement;
  findRegexToggle: HTMLButtonElement;
  findStatus: HTMLSpanElement;
  splitPane: HTMLDivElement;
  resizer: HTMLDivElement;
  consoleEl: HTMLDivElement;
  clearConsoleBtn: HTMLButtonElement;
  varsToggleBtn: HTMLButtonElement;
  varsPane: HTMLDivElement;
  varsList: HTMLDivElement;
  varsMeta: HTMLDivElement;
  aboutOverlay: HTMLDivElement;
  closeAboutBtn: HTMLButtonElement;
  licenseLink: HTMLAnchorElement;
  licenseOverlay: HTMLDivElement;
  closeLicenseBtn: HTMLButtonElement;
  aboutVersion: HTMLSpanElement;
  aboutBuildTime: HTMLSpanElement;
  aboutCommitHash: HTMLSpanElement;
  settingsOverlay: HTMLDivElement;
  closeSettingsBtn: HTMLButtonElement;
  openShortcutsBtn: HTMLButtonElement;
  shortcutsOverlay: HTMLDivElement;
  closeShortcutsBtn: HTMLButtonElement;
  printOverlay: HTMLDivElement;
  printBtn: HTMLButtonElement;
  printCancelBtn: HTMLButtonElement;
  printConfirmBtn: HTMLButtonElement;
  printIncludeCode: HTMLInputElement;
  printIncludeOutput: HTMLInputElement;
  printLineNumbers: HTMLInputElement;
  printWrapLines: HTMLInputElement;
  printBranding: HTMLInputElement;
  printTimestamp: HTMLInputElement;
  printContentNote: HTMLDivElement;
  exportRoot: HTMLDivElement;
  historyOverlay: HTMLDivElement;
  historyList: HTMLDivElement;
  historyDiff: HTMLDivElement;
  historyCloseBtn: HTMLButtonElement;
  historyRestoreBtn: HTMLButtonElement;
  shareWarnOverlay: HTMLDivElement;
  shareWarnText: HTMLDivElement;
  shareWarnHint: HTMLDivElement;
  shareWarnCancelBtn: HTMLButtonElement;
  shareWarnDownloadBtn: HTMLButtonElement;
  shareWarnConfirmBtn: HTMLButtonElement;
  projectImportOverlay: HTMLDivElement;
  projectImportText: HTMLDivElement;
  projectImportCancelBtn: HTMLButtonElement;
  projectImportConfirmBtn: HTMLButtonElement;
  asyncWarnOverlay: HTMLDivElement;
  asyncWarnText: HTMLDivElement;
  asyncWarnCancelBtn: HTMLButtonElement;
  asyncWarnConfirmBtn: HTMLButtonElement;
  shareToast: HTMLDivElement;
  shareToastTitle: HTMLDivElement;
  shareToastDesc: HTMLDivElement;
  shareToastIcon: HTMLSpanElement;
  sysToast: HTMLDivElement;
  sysToastTitle: HTMLDivElement;
  sysToastDesc: HTMLDivElement;
  sysToastIcon: HTMLSpanElement;
  sysToastActions: HTMLDivElement;
  sysToastActionBtn: HTMLButtonElement;
  tabStrip: HTMLDivElement;
  newTabBtn: HTMLButtonElement;
  editorStatus: HTMLDivElement;
  hintRun: HTMLSpanElement;
  hintOpen: HTMLSpanElement;
  hintSave: HTMLSpanElement;
  hintSettings: HTMLSpanElement;
  hintPrint: HTMLSpanElement;
  isolationBanner: HTMLDivElement;
  isolationBannerClose: HTMLButtonElement;
  editorSizeRange: HTMLInputElement;
  consoleSizeRange: HTMLInputElement;
  editorSizeLabel: HTMLSpanElement;
  consoleSizeLabel: HTMLSpanElement;
  wrapToggle: HTMLInputElement;
  activeLineToggle: HTMLInputElement;
  splitToggle: HTMLInputElement;
  workspaceFeatureToggle: HTMLInputElement;
  execTimeToggle: HTMLInputElement;
  themeAuto: HTMLInputElement;
  themeLight: HTMLInputElement;
  themeDark: HTMLInputElement;
  themeGroup: HTMLDivElement;
  resetPrefsBtn: HTMLButtonElement;
  shortcutBody: HTMLTableSectionElement;
  dynamicStyles: HTMLStyleElement;
};

export function getDomRefs(): DomRefs {
  return {
    runBtn: byId<HTMLButtonElement>("runBtn"),
    runModeBtn: byId<HTMLButtonElement>("runModeBtn"),
    runGroup: byId<HTMLDivElement>("runGroup"),
    runMenu: byId<HTMLDivElement>("runMenu"),
    runAllBtn: byId<HTMLButtonElement>("runAllBtn"),
    runSelBtn: byId<HTMLButtonElement>("runSelBtn"),
    runCellBtn: byId<HTMLButtonElement>("runCellBtn"),
    runLabel: byId<HTMLSpanElement>("runLabel"),
    openBtn: byId<HTMLButtonElement>("openBtn"),
    saveBtn: byId<HTMLButtonElement>("saveBtn"),
    workspaceToggleBtn: byId<HTMLButtonElement>("workspaceToggleBtn"),
    shareBtn: byId<HTMLButtonElement>("shareBtn"),
    fileInput: byId<HTMLInputElement>("fileInput"),
    directoryInput: byId<HTMLInputElement>("directoryInput"),
    moreBtn: byId<HTMLButtonElement>("moreBtn"),
    moreMenu: byId<HTMLDivElement>("moreMenu"),
    shareMenuBtn: byId<HTMLButtonElement>("shareMenuBtn"),
    historyBtn: byId<HTMLButtonElement>("historyBtn"),
    shortcutsBtn: byId<HTMLButtonElement>("shortcutsBtn"),
    resetBtn: byId<HTMLButtonElement>("resetBtn"),
    settingsBtn: byId<HTMLButtonElement>("settingsBtn"),
    aboutBtn: byId<HTMLButtonElement>("aboutBtn"),
    undoBtn: byId<HTMLButtonElement>("undoBtn"),
    redoBtn: byId<HTMLButtonElement>("redoBtn"),
    findBtn: byId<HTMLButtonElement>("findBtn"),
    wrapBtn: byId<HTMLButtonElement>("wrapBtn"),
    editorActionsBtn: byId<HTMLButtonElement>("editorActionsBtn"),
    editorActionsMenu: byId<HTMLDivElement>("editorActionsMenu"),
    renameTabBtn: byId<HTMLButtonElement>("renameTabBtn"),
    closeTabBtn: byId<HTMLButtonElement>("closeTabBtn"),
    workspaceLayout: byId<HTMLDivElement>("workspaceLayout"),
    editorPane: byId<HTMLDivElement>("editorPane"),
    workspacePane: byId<HTMLElement>("workspacePane"),
    workspaceResizer: byId<HTMLDivElement>("workspaceResizer"),
    workspaceNewBtn: byId<HTMLButtonElement>("workspaceNewBtn"),
    workspaceUploadBtn: byId<HTMLButtonElement>("workspaceUploadBtn"),
    workspaceRenameBtn: byId<HTMLButtonElement>("workspaceRenameBtn"),
    workspaceDownloadBtn: byId<HTMLButtonElement>("workspaceDownloadBtn"),
    workspaceDeleteBtn: byId<HTMLButtonElement>("workspaceDeleteBtn"),
    workspaceCloseBtn: byId<HTMLButtonElement>("workspaceCloseBtn"),
    workspaceMeta: byId<HTMLDivElement>("workspaceMeta"),
    workspaceTree: byId<HTMLDivElement>("workspaceTree"),
    workspaceUploadOverlay: byId<HTMLDivElement>("workspaceUploadOverlay"),
    workspaceUploadFileChoiceBtn: byId<HTMLButtonElement>("workspaceUploadFileChoiceBtn"),
    workspaceUploadFolderChoiceBtn: byId<HTMLButtonElement>("workspaceUploadFolderChoiceBtn"),
    workspaceUploadCancelBtn: byId<HTMLButtonElement>("workspaceUploadCancelBtn"),
    editorSurface: byId<HTMLDivElement>("editorSurface"),
    filePreviewPane: byId<HTMLDivElement>("filePreviewPane"),
    filePreviewMeta: byId<HTMLDivElement>("filePreviewMeta"),
    filePreviewBody: byId<HTMLDivElement>("filePreviewBody"),
    findBar: byId<HTMLDivElement>("findBar"),
    findInput: byId<HTMLInputElement>("findInput"),
    findCount: byId<HTMLSpanElement>("findCount"),
    findReplaceModeBtn: byId<HTMLButtonElement>("findReplaceModeBtn"),
    findPrevBtn: byId<HTMLButtonElement>("findPrevBtn"),
    findNextBtn: byId<HTMLButtonElement>("findNextBtn"),
    findCloseBtn: byId<HTMLButtonElement>("findCloseBtn"),
    replaceRow: byId<HTMLDivElement>("replaceRow"),
    replaceInput: byId<HTMLInputElement>("replaceInput"),
    replaceBtn: byId<HTMLButtonElement>("replaceBtn"),
    replaceAllBtn: byId<HTMLButtonElement>("replaceAllBtn"),
    findCaseToggle: byId<HTMLButtonElement>("findCaseToggle"),
    findWordToggle: byId<HTMLButtonElement>("findWordToggle"),
    findRegexToggle: byId<HTMLButtonElement>("findRegexToggle"),
    findStatus: byId<HTMLSpanElement>("findStatus"),
    splitPane: byId<HTMLDivElement>("splitPane"),
    resizer: byId<HTMLDivElement>("dragbar"),
    consoleEl: byId<HTMLDivElement>("console"),
    clearConsoleBtn: byId<HTMLButtonElement>("clearConsoleBtn"),
    varsToggleBtn: byId<HTMLButtonElement>("varsToggleBtn"),
    varsPane: byId<HTMLDivElement>("varsPane"),
    varsList: byId<HTMLDivElement>("varsList"),
    varsMeta: byId<HTMLDivElement>("varsMeta"),
    aboutOverlay: byId<HTMLDivElement>("aboutOverlay"),
    closeAboutBtn: byId<HTMLButtonElement>("closeAboutBtn"),
    licenseLink: byId<HTMLAnchorElement>("licenseLink"),
    licenseOverlay: byId<HTMLDivElement>("licenseOverlay"),
    closeLicenseBtn: byId<HTMLButtonElement>("closeLicenseBtn"),
    aboutVersion: byId<HTMLSpanElement>("aboutVersion"),
    aboutBuildTime: byId<HTMLSpanElement>("aboutBuildTime"),
    aboutCommitHash: byId<HTMLSpanElement>("aboutCommitHash"),
    settingsOverlay: byId<HTMLDivElement>("settingsOverlay"),
    closeSettingsBtn: byId<HTMLButtonElement>("closeSettingsBtn"),
    openShortcutsBtn: byId<HTMLButtonElement>("openShortcutsBtn"),
    shortcutsOverlay: byId<HTMLDivElement>("shortcutsOverlay"),
    closeShortcutsBtn: byId<HTMLButtonElement>("closeShortcutsBtn"),
    printOverlay: byId<HTMLDivElement>("printOverlay"),
    printBtn: byId<HTMLButtonElement>("printBtn"),
    printCancelBtn: byId<HTMLButtonElement>("printCancelBtn"),
    printConfirmBtn: byId<HTMLButtonElement>("printConfirmBtn"),
    printIncludeCode: byId<HTMLInputElement>("printIncludeCode"),
    printIncludeOutput: byId<HTMLInputElement>("printIncludeOutput"),
    printLineNumbers: byId<HTMLInputElement>("printLineNumbers"),
    printWrapLines: byId<HTMLInputElement>("printWrapLines"),
    printBranding: byId<HTMLInputElement>("printBranding"),
    printTimestamp: byId<HTMLInputElement>("printTimestamp"),
    printContentNote: byId<HTMLDivElement>("printContentNote"),
    exportRoot: byId<HTMLDivElement>("exportRoot"),
    historyOverlay: byId<HTMLDivElement>("historyOverlay"),
    historyList: byId<HTMLDivElement>("historyList"),
    historyDiff: byId<HTMLDivElement>("historyDiff"),
    historyCloseBtn: byId<HTMLButtonElement>("historyCloseBtn"),
    historyRestoreBtn: byId<HTMLButtonElement>("historyRestoreBtn"),
    shareWarnOverlay: byId<HTMLDivElement>("shareWarnOverlay"),
    shareWarnText: byId<HTMLDivElement>("shareWarnText"),
    shareWarnHint: byId<HTMLDivElement>("shareWarnHint"),
    shareWarnCancelBtn: byId<HTMLButtonElement>("shareWarnCancelBtn"),
    shareWarnDownloadBtn: byId<HTMLButtonElement>("shareWarnDownloadBtn"),
    shareWarnConfirmBtn: byId<HTMLButtonElement>("shareWarnConfirmBtn"),
    projectImportOverlay: byId<HTMLDivElement>("projectImportOverlay"),
    projectImportText: byId<HTMLDivElement>("projectImportText"),
    projectImportCancelBtn: byId<HTMLButtonElement>("projectImportCancelBtn"),
    projectImportConfirmBtn: byId<HTMLButtonElement>("projectImportConfirmBtn"),
    asyncWarnOverlay: byId<HTMLDivElement>("asyncWarnOverlay"),
    asyncWarnText: byId<HTMLDivElement>("asyncWarnText"),
    asyncWarnCancelBtn: byId<HTMLButtonElement>("asyncWarnCancelBtn"),
    asyncWarnConfirmBtn: byId<HTMLButtonElement>("asyncWarnConfirmBtn"),
    shareToast: byId<HTMLDivElement>("shareToast"),
    shareToastTitle: byId<HTMLDivElement>("shareToastTitle"),
    shareToastDesc: byId<HTMLDivElement>("shareToastDesc"),
    shareToastIcon: byId<HTMLSpanElement>("shareToastIcon"),
    sysToast: byId<HTMLDivElement>("sysToast"),
    sysToastTitle: byId<HTMLDivElement>("sysToastTitle"),
    sysToastDesc: byId<HTMLDivElement>("sysToastDesc"),
    sysToastIcon: byId<HTMLSpanElement>("sysToastIcon"),
    sysToastActions: byId<HTMLDivElement>("sysToastActions"),
    sysToastActionBtn: byId<HTMLButtonElement>("sysToastActionBtn"),
    tabStrip: byId<HTMLDivElement>("tabStrip"),
    newTabBtn: byId<HTMLButtonElement>("newTabBtn"),
    editorStatus: byId<HTMLDivElement>("editorStatus"),
    hintRun: byId<HTMLSpanElement>("hintRun"),
    hintOpen: byId<HTMLSpanElement>("hintOpen"),
    hintSave: byId<HTMLSpanElement>("hintSave"),
    hintSettings: byId<HTMLSpanElement>("hintSettings"),
    hintPrint: byId<HTMLSpanElement>("hintPrint"),
    isolationBanner: byId<HTMLDivElement>("isolationBanner"),
    isolationBannerClose: byId<HTMLButtonElement>("isolationBannerClose"),
    editorSizeRange: byId<HTMLInputElement>("editorSizeRange"),
    consoleSizeRange: byId<HTMLInputElement>("consoleSizeRange"),
    editorSizeLabel: byId<HTMLSpanElement>("editorSizeLabel"),
    consoleSizeLabel: byId<HTMLSpanElement>("consoleSizeLabel"),
    wrapToggle: byId<HTMLInputElement>("wrapToggle"),
    activeLineToggle: byId<HTMLInputElement>("activeLineToggle"),
    splitToggle: byId<HTMLInputElement>("splitToggle"),
    workspaceFeatureToggle: byId<HTMLInputElement>("workspaceFeatureToggle"),
    execTimeToggle: byId<HTMLInputElement>("execTimeToggle"),
    themeAuto: byId<HTMLInputElement>("themeAuto"),
    themeLight: byId<HTMLInputElement>("themeLight"),
    themeDark: byId<HTMLInputElement>("themeDark"),
    themeGroup: byId<HTMLDivElement>("themeGroup"),
    resetPrefsBtn: byId<HTMLButtonElement>("resetPrefsBtn"),
    shortcutBody: byId<HTMLTableSectionElement>("shortcutBody"),
    dynamicStyles: byId<HTMLStyleElement>("dynamicStyles")
  };
}
