// Generated by scripts/build-version.mjs. Do not edit.
export const APP_VERSION = "3.4";
export const BUILD_TIME = "2026-02-13T06:50:52.465Z";
export const COMMIT_HASH = "bbb7c45fde6d129619501911c3a16fc3a8df6701";
