// Generated by scripts/build-version.mjs. Do not edit.
export const APP_VERSION = "3.4";
export const BUILD_TIME = "2026-02-02T04:07:05.149Z";
export const COMMIT_HASH = "827937fb43d090a6fdda69380ed2e5611b744db2";
