// Generated by scripts/build-version.mjs. Do not edit.
export const APP_VERSION = "3.3";
export const BUILD_TIME = "2026-02-01T10:52:23.998Z";
export const COMMIT_HASH = "a2adc9b0c28b84a7d6b6eeba92a5e945d0f45524";
